schema_version: 1

context:
  # Version of package that this release corresponds to.
  version: "2026.0.0"

package:
  name: at-cascade
  version: ${{ version }}

source:
  url: https://github.com/bradbell/at_cascade/archive/${{ version }}.tar.gz
  sha256: 22235b2747f8fb30b75ae547b5e0255615a25ad68ca98ee3193d5b1c0c78e660
  #
  patches:
    # patches for this version. 
    - ${{ version }}.patch

build:
  number: 1
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - pip
    - dismod-at >=2026.0.0
    - numpy
    - scipy
  run:
    - python
    - dismod-at >=2026.0.0
    - numpy
    - scipy

tests:
  - python:
      imports:
        - at_cascade
      pip_check: true
  # Run one of the sandbox tests using the installed version of at_cascade.
  - script:
      # python example/csv/sim_fit_pred.py
      interpreter: python
      content: exec( open('example/csv/sim_fit_pred.py').read() )
    requirements:
    files:
      source:
        - example/csv/sim_fit_pred.py

about:
  summary: Cascading dismod_at from parent to child regions
  license: AGPL-3.0-or-later
  license_file: agpl-3.0.txt
  homepage: https://at-cascade.readthedocs.io/stable-2025/
  repository: https://github.com/bradbell/at_cascade
  documentation: https://at-cascade.readthedocs.io/stable-2025/

extra:
  recipe-maintainers:
    - bradbell
